name: AWS SQS Scheduler - Test & Publish

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'packages/aws-sqs/**'
      - '.github/workflows/aws-sqs.yml'

  # This should work with GitHub releases as well
  # But will publish on release created, not necessarily published
  push:
    tags:
      - v**-aws-sqs

jobs:
  test:
    name: Test @control/assembly-line-aws-sqs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: actions/cache@master
        id: cache-node-modules
        with:
          path: node_modules
          key: npm-${{ hashFiles('packages/aws-sqs/package-lock.json') }}-aws-sqs

      # Cannot if-cache because we need to initialize all
      # packages on the chain (so we can require @control/assembly-line)
      - run: npm i
        if: steps.cache-node-modules.outputs.cache-hit != 'true'

      - run: npm test -w packages/aws-sqs

  publish:
    name: Publish @control/assembly-line-aws-sqs
    runs-on: ubuntu-latest


    needs:
      - test

    if: ${{ github.event_name == 'push' }}

    steps:
      - name: Get version
        id: version
        # TODO: maybe check refs/tags as well
        run: echo "version=$(echo "${{ github.event.push.ref }}" | sed -e 's/\-aws-sqs//')" >> $GITHUB_OUTPUT

      - uses: actions/checkout@master

      - run: npm version ${{ steps.version.outputs.version }} --no-git-tag-version
        name: Set package version ${{ steps.version.outputs.version }}
        working-directory: packages/aws-sqs

      - run: npm publish
        working-directory: packages/aws-sqs
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
