name: Compatibility testing

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    name: Test all packages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: actions/cache@master
        id: cache-node-modules
        with:
          path: node_modules
          key: npm-${{ hashFiles('package-lock.json') }}-compat

      - run: npm i
        if: steps.cache-node-modules.outputs.cache-hit != 'true'

      - run: npm test -ws
