name: Core - Test & Publish

on:
  pull_request:
    types: [opened, synchronize]
    paths: 
      - 'packages/core/**'
      - '.github/workflows/core.yml'

  # This should work with GitHub releases as well
  # But will publish on release created, not necessarily published
  push:
    tags:
      - v**-core

jobs:
  test:
    name: Test @control/assembly-line
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - run: npm i -ws
        if: steps.cache-node-modules.outputs.cache-hit != 'true'

      - run: npm test -w packages/core

  publish:
    name: Publish @control/gassembly-line
    runs-on: ubuntu-latest

    needs:
      - test

    if: ${{ github.event_name == 'push' }}

    steps:
      - name: Get version
        id: version
        # TODO: maybe check refs/tags as well
        run: echo "version=$(echo "${{ github.event.push.ref }}" | sed -e 's/\-core//')" >> $GITHUB_OUTPUT
        working-directory: packages/core

      - uses: actions/checkout@master

      - run: npm version ${{ steps.version.outputs.version }} --no-git-tag-version
        name: Set package version ${{ steps.version.outputs.version }}
        working-directory: packages/core


      - run: npm publish
        working-directory: packages/core
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
