name: Core - Test & Publish

on:
  pull_request:
    types: [opened, synchronize]
    paths: 'packages/core/**'

  push:
    tags:
      - v**-core

defaults:
  run:
    working-directory: packages/core

jobs:
  test:
    name: Test @control/assembly-line
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - run: npm i

      - run: npm test

  publish:
    name: Publish @control/gassembly-line
    runs-on: ubuntu-latest

    needs:
      - test

    if: ${{ github.event_name == 'push' }}

    steps:
      - name: Get version
        id: version
        # TODO: maybe check refs/tags as well
        run: echo "version=$(echo "${{ github.event.push.ref }}" | sed -e 's/\-core//')" >> $GITHUB_OUTPUT

      - uses: actions/checkout@master

      - run: npm version ${{ steps.version.outputs.version }} --no-git-tag-version
        name: Set package version ${{ steps.version.outputs.version }}

      - run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
